language: python
sudo: false
python:
  - "3.4"

install:
  - pip install -U twine
  - make install
  - ./env/bin/pip install coveralls

script:
  - make checkstyle
  - make test

after_success:
  - ./env/bin/coveralls

deploy:
- provider: pypi
  user: {{ cookiecutter.github_username }}
  password:
    secure: "super secure pypi hashed password using the travis gem"
  on:
    tags: true
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.repo_name }}

notifications:
  email: false
